sudo: required
dist: trusty

language:
  - cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-virtualenv python3 python3-dev
  - sudo apt-get install libfuse-dev valgrind gcc libattr1-dev fuse wget lcov
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf

compiler:
  - gcc

script:
  - virtualenv -p /usr/bin/python3 python_venv
  - source python_venv/bin/activate
  - easy_install xattr
  - easy_install pathlib
  - mkdir -p build && cd build
  - cmake -DENABLE_CODECOVERAGE=1 -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - make fuse_xattrs_coverage

after_failure:
  - cat build/Testing/Temporary/LastTest.log
